In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math


# Standard matrix multiplication

In [3]:
## For matrix multiplication to be valid, inner dimensions must match.

m = 4
n = 3
k = 6

# making some matrices
A = np.random.randn(m,n)
B = np.random.randn(n,k)
C = np.random.randn(m,k)

print("The multiplication between A and B is:\n",np.matmul(A,B))
print("\n")


print("The multiplication between transpose of A and C is:\n",np.matmul(np.matrix.transpose(A),C))
print("\n")
print("The multiplication between B and transpose of B is:\n",np.matmul(B,np.matrix.transpose(B)))
print("\n")
print("The multiplication between transpose of B and B is:\n",np.matmul(np.matrix.transpose(B),B))
print("\n")


The multiplication between A and B is:
 [[ 0.06360428 -0.52640105 -0.10647328  0.25873949  0.07690304 -1.76467679]
 [-1.56337932 -0.56756885 -0.88423823  0.33343246 -0.15772589  0.10711761]
 [ 0.00457305 -0.61105758 -0.31719969  0.21754356 -0.38206632 -1.98513938]
 [-1.77796642 -0.66984875 -1.65538429  0.05098445 -2.0197829  -0.04406698]]


The multiplication between transpose of A and C is:
 [[-0.79081979  1.13787738  0.79710915  1.75206161  0.75289861 -1.87467664]
 [ 0.12328988 -0.95987819 -0.06288095 -0.17929264 -2.24333523  1.74452775]
 [ 0.02345515  1.26680772 -0.58776639  0.93226778 -0.36560317 -1.36130775]]


The multiplication between B and transpose of B is:
 [[ 3.26683593 -0.8910902  -2.0459836 ]
 [-0.8910902   3.19017365  1.69680421]
 [-2.0459836   1.69680421  8.79767029]]


The multiplication between transpose of B and B is:
 [[ 4.27973743  0.61307202  1.48953251 -0.81006121 -1.41646582 -3.40038709]
 [ 0.61307202  0.44768277  0.39732418 -0.2464266   0.01067644  0.67809143]



# Matrix-vector multiplication


In [6]:
# number of elements
m = 4

# creating a matrix
N = np.round( 10*np.random.randn(m,m) )

# creating a vector
w = np.array([-1, 0, 1, 2])
print("Matrix A is:\n",A)
print("\n")
print("Vector w is:\n",w)
print("\n")
#The @ symbol is used for matrix multiplication in python.
print("The multiplication ofa matrix and vector results in a vector: \n",N@w)


Matrix A is:
 [[ 0.09756867  0.90357078  0.21820366]
 [-0.35171022  0.64613633 -0.6747352 ]
 [-0.20473822  0.98279826  0.17931993]
 [-1.5900963   0.5675367  -0.90023278]]


Vector w is:
 [-1  0  1  2]


The multiplication ofa matrix and vector results in a vector: 
 [-50.  -8.  -6.  19.]
