In [2]:
import numpy as np
from sympy import *
import matplotlib.pyplot as plt

# Inverse of a matrix


In [4]:
m = 3

# generate random matrix
A = np.random.randn(m,m)

# computing its inverse
Ainv = np.linalg.inv(A)

# Confirming whether its the right inverse of A or not 
I = A@Ainv

print("The matrix A is:\n",A)
print("\n")
print("Inverse of A is:\n",Ainv)
print("\n")
print("A@Ainv= I\n",I)  #The result is matrix I but the off diagonal elements are not zero rather because of computational errors it's very close to 0



The matrix A is:
 [[-0.36377796 -1.6437536  -2.1943572 ]
 [ 0.16590797  2.03498131  1.29181871]
 [-1.98688862  0.16758107 -1.31627606]]


Inverse of A is:
 [[ 0.72013585  0.62966364 -0.58257082]
 [ 0.58413168  0.96540537 -0.02633554]
 [-1.01266016 -0.82755274  0.11630539]]


A@Ainv= I
 [[ 1.00000000e+00  1.02354210e-16  1.56096010e-17]
 [-4.07158866e-17  1.00000000e+00  4.40228933e-18]
 [-9.81758564e-17 -4.99351643e-17  1.00000000e+00]]


# Computing the inverse of a matrix via row reduction


In [12]:
# defining matrix size
m = 3

# creating matrix of random integers via using sympy
A = Matrix( np.round(10*np.random.randn(m,m)) )

# augmenting matrix A and identity matrix
Aaug = Matrix( np.concatenate((A,np.eye(m,m)),axis=1) )
print('Size of Aaug:',Aaug.shape)

# inverse using rref technique
Asol = Aaug.rref()
A_inv_rref = Asol[0]
A_inv_rref = A_inv_rref[:,m:m*2]

# inverse of a matrix
Ainv = A.inv()

print("The matrix A is:\n",A)
print("\n")
print("The inverse of matrix A via rref is:\n",A_inv_rref)
print("\n")
print("The inverse of matrix A is:\n",Ainv)



Size of Aaug: (3, 6)
The matrix A is:
 Matrix([[-16.0000000000000, 5.00000000000000, -6.00000000000000], [-2.00000000000000, 7.00000000000000, 7.00000000000000], [-1.00000000000000, 2.00000000000000, -8.00000000000000]])


The inverse of matrix A via rref is:
 Matrix([[-0.0709219858156028, 0.0283687943262411, 0.0780141843971631], [-0.0233029381965552, 0.123606889564336, 0.125633232016211], [0.00303951367781155, 0.0273556231003040, -0.103343465045593]])


The inverse of matrix A is:
 Matrix([[-0.0709219858156028, 0.0283687943262411, 0.0780141843971631], [-0.0233029381965552, 0.123606889564336, 0.125633232016211], [0.00303951367781155, 0.0273556231003040, -0.103343465045593]])


# Left inverse and right inverse


In [13]:
# Left and right inverse are defined for rectangular matrices
m = 6
n = 3

# creating matrices
A = np.random.randn(m,n)
AtA = np.matrix.transpose(A)@A
AAt = A@np.matrix.transpose(A)

# ranks of matrix
print('Rank of A^TA:', np.linalg.matrix_rank(AtA) ) 
print("\n")
print('Rank of AA^T:', np.linalg.matrix_rank(AAt) ) 
print("\n")

# left inverse

Aleft = np.linalg.inv(AtA)@np.matrix.transpose(A)
print("The left inverse of matrix A is:\n",Aleft)
print("\n")

# right inverse
Aright = np.matrix.transpose(A)@np.linalg.inv(AAt)
print("The right inverse of matrix A is:\n",Aright)
print("\n")





Rank of A^TA: 3


Rank of AA^T: 3


The left inverse of matrix A is:
 [[ 0.10959941 -0.09484428 -0.01027413  0.29903391 -0.12365886  0.10590027]
 [-0.04529371  0.34342617 -0.36991102  0.04538032  0.0469861   0.01468823]
 [ 0.1759275   0.05243263 -0.42533001 -0.14093609  0.09581985 -0.19309322]]


The right inverse of matrix A is:
 [[-2.      0.     -2.     -2.     -4.      0.    ]
 [ 1.0625  1.25    0.25    1.     -0.25   -1.    ]
 [ 2.      0.75    1.5     2.      8.     -1.    ]]


