In [1]:
import numpy as np

In [2]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print("Square matrix is: \n", S)
print("\n")

print("Rectangular matrix is:\n", R)

Square matrix is: 
 [[ 0.89796844  1.21067043 -0.5175889   0.06398313 -0.58235492]
 [ 1.34889972  1.6336912  -0.11834795  0.06957899  2.55074098]
 [ 1.63802509  1.66189159 -0.5252638   0.45071245 -2.587278  ]
 [ 0.21972451 -0.98117829 -1.27482798 -0.65013073 -1.02862072]
 [ 1.49391908  0.43552445 -1.01586744  0.65612558 -2.01427382]]


Rectangular matrix is:
 [[-0.17405368 -0.93317141]
 [-1.5681006  -1.01578164]
 [ 1.19365298  0.60128238]
 [ 0.20652982 -0.39641344]
 [ 2.30532123 -0.72102892]]


In [3]:
# identity
I = np.eye(3)
print("The 3x3 identity matrix is:\n",I)
print("\n")

# zeros
Z = np.zeros((4,4))
print("The zeores matrix is:\n", Z)
print("\n")

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print("The diagonal matrix is:\n",D)



The 3x3 identity matrix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The zeores matrix is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The diagonal matrix is:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [4]:
# creating triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print("The original matrix is: \n", S)
print("\n")
print("The upper triangular matrix is: \n",U)
print("\n")
print("The lower triangular matrix is:\n",L)



The original matrix is: 
 [[-0.28156086  1.69454269 -0.04573187  0.09832132 -0.20454803]
 [-0.07101951 -0.86552169 -0.18550793  2.3582911   1.2274644 ]
 [-0.57429474  0.46538448 -1.82644221 -0.22053839  0.68368042]
 [-0.20878973 -0.05871542  0.23721317  0.81734584  1.07436294]
 [ 0.86178271 -1.21959403  0.06211862 -1.24960019 -0.43702536]]


The upper triangular matrix is: 
 [[-0.28156086  1.69454269 -0.04573187  0.09832132 -0.20454803]
 [ 0.         -0.86552169 -0.18550793  2.3582911   1.2274644 ]
 [ 0.          0.         -1.82644221 -0.22053839  0.68368042]
 [ 0.          0.          0.          0.81734584  1.07436294]
 [ 0.          0.          0.          0.         -0.43702536]]


The lower triangular matrix is:
 [[-0.28156086  0.          0.          0.          0.        ]
 [-0.07101951 -0.86552169  0.          0.          0.        ]
 [-0.57429474  0.46538448 -1.82644221  0.          0.        ]
 [-0.20878973 -0.05871542  0.23721317  0.81734584  0.        ]
 [ 0.86178271 -1.21

In [5]:
# concatenate matrices (sizes must match!)
A = np.random.randn(4,4)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print("Matrix A is: \n",A)
print("\n")
print("Matrix B is:\n",B)
print("\n")
print("Concatenation result is:\n",C)

Matrix A is: 
 [[-0.19355784 -0.26892122 -0.61002294  0.33116127]
 [-0.54986612 -0.89108519 -1.01146847  0.5288658 ]
 [ 0.79636485 -0.02223278  0.29919582 -0.89493757]
 [ 0.59823422  1.99225545  0.88231256 -0.72830229]]


Matrix B is:
 [[-1.62886768 -0.20188444  0.79598586 -0.54686232]
 [ 0.70426673  0.51445775  1.91721645 -0.7143191 ]
 [ 1.00268925  0.03705049 -1.3243772  -0.80432843]
 [-0.35065948  1.30390374  0.00641839  0.73728505]]


Concatenation result is:
 [[-0.19355784 -0.26892122 -0.61002294  0.33116127 -1.62886768 -0.20188444
   0.79598586 -0.54686232]
 [-0.54986612 -0.89108519 -1.01146847  0.5288658   0.70426673  0.51445775
   1.91721645 -0.7143191 ]
 [ 0.79636485 -0.02223278  0.29919582 -0.89493757  1.00268925  0.03705049
  -1.3243772  -0.80432843]
 [ 0.59823422  1.99225545  0.88231256 -0.72830229 -0.35065948  1.30390374
   0.00641839  0.73728505]]


# Matrix Addition and subtraction

In [6]:
# creating random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

#A+B wont add because the dimensions are not same.

print("Matrix A is:\n",A)
print("\n")

print("Matrix B is:\n",B)
print("\n")


print("Matrix C is:\n",C)
print("\n")
print("The addition of A and C is:\n",A+C)
print("\n")
print("The Subtraction of A and C is:\n",A-C)





Matrix A is:
 [[ 0.46286125  2.42562645 -1.34076184 -1.11595835]
 [-0.55043811 -0.90349136  0.05073095  0.44339038]
 [-2.80933403  0.80817771 -0.32236278 -0.25749719]
 [-1.1077174  -0.71409183  1.18207454 -0.18265602]
 [ 0.43051915 -0.28783514  3.54953979  0.74007606]]


Matrix B is:
 [[ 1.43285398 -0.17151526 -1.58499217]
 [ 1.03666544 -0.40507854  0.67088018]
 [-1.18365105 -0.32581877  1.64226761]
 [-0.3547737  -0.9255086  -0.40262037]
 [-0.43095449 -0.3204578  -0.71178787]]


Matrix C is:
 [[ 0.3250535   0.64191245  1.17620286  1.21975998]
 [-1.31642671 -0.42677085  1.01983091 -1.12422164]
 [ 2.37253545  0.65065993 -1.10205239  0.26598802]
 [ 1.91217647 -1.19554826 -1.27562757 -1.38842026]
 [-0.35612851 -1.00969586 -0.08506885  0.72894955]]


The addition of A and C is:
 [[ 0.78791475  3.0675389  -0.16455898  0.10380163]
 [-1.86686482 -1.33026221  1.07056186 -0.68083126]
 [-0.43679858  1.45883764 -1.42441517  0.00849082]
 [ 0.80445907 -1.90964009 -0.09355304 -1.57107628]
 [ 0.074390

# Matrix-scalar multiplication



In [7]:
# defining matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print("Pre-multiplication:\n", M*s )
print("\n")
print("Post-multiplication:\n", s*M )
print("\n")
print("Both are same")

Pre-multiplication:
 [[ 2  4]
 [ 4 10]]


Post-multiplication:
 [[ 2  4]
 [ 4 10]]


Both are same


# Diagonal and trace of a matrix


In [8]:
M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# The two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print("When input is matrix and output is a vector:\n",d)
print("\n")
print("When input is vector and output is a matrix:\n",D)


When input is matrix and output is a vector:
 [-2. -0. -4. -9.]


When input is vector and output is a matrix:
 [[-2.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0. -4.  0.]
 [ 0.  0.  0. -9.]]


In [9]:
# Trace is the sum of diagonal elements
tr = np.trace(M)
print("The trace of Matrix M is:",tr)

The trace of Matrix M is: -15.0
