# NumPy Array Operations And Indexing

# NumPy Array Indexing

In [1]:
import numpy as np

In [3]:
myarray= np.arange(1,11)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Indexing in NumPy arrays
#It works just like python lists.
myarray[2]

3

In [16]:
#grabbing elements from start position to stop position.
myarray[0:5]

array([1, 2, 3, 4, 5])

In [17]:
#grabbing elements by skipping n elements (step position)
myarray[0:10:2]  #here, n=2 

array([1, 3, 5, 7, 9])

In [20]:
#grabbing all the elements after an element on a certain position
myarray[5:]    #here, I want all the elements after the element which is on position 5

array([ 6,  7,  8,  9, 10])

In [21]:
#grabbing all the elements till an element on a certain position
myarray[:5]    #here, I want all the elements before the element which is on position 5

array([1, 2, 3, 4, 5])

In [22]:
#creating a 2_D array.
two_d_array= np.arange(0,25).reshape(5,5)
two_d_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
#grabbing a particular element
two_d_array[0,4] #grabbing the element of row 1 and column 5, indexing in python starts from 0

4

In [26]:
#grabbing certain rows and columns
two_d_array[1:3, 1:3] #grabbing subsection of a 2d array. grabbed all the elements of (second and third row) and (column and third column)

array([[ 6,  7],
       [11, 12]])

# NumPy Operations

In [51]:
#Creating an array from 10-19
array1=  np.arange(10,20)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
#creating an array from 20-29
array2=  np.arange(20,30)
array2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
#Adding two same dimensional arrays
array1+array2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [54]:
#Subtracting two same dimensional arrays
array1-array2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [55]:
#Multiplying an array with a scalar
new_array= array1*100
new_array

array([1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900])

In [56]:
#Multiplying 2 arrays of same dimensions
new_array * array2

array([20000, 23100, 26400, 29900, 33600, 37500, 41600, 45900, 50400,
       55100])

In [57]:
#calculating square root of every element of an array
np.sqrt(new_array)

array([31.6227766 , 33.1662479 , 34.64101615, 36.05551275, 37.41657387,
       38.72983346, 40.        , 41.23105626, 42.42640687, 43.58898944])