In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *


# Singular value decomposition


In [11]:
#U and V are orthogonal matrices with orthonormal eigenvectors
#S is a diagonal matrix with elements equal to the root of the positive eigenvalues of AAᵀ or Aᵀ A 
# the matrix
A = [ [3,0,5], [8,1,3] ]

U,S,V = np.linalg.svd(A)
print("The matrix U is:\n",U)
print("\n")
print("The matrix S is:\n",S)
print("\n")
print("The matrix V is:\n",V)

The matrix U is:
 [[-0.52138438 -0.85332193]
 [-0.85332193  0.52138438]]


The matrix S is:
 [9.89086518 3.18916698]


The matrix V is:
 [[-0.84833111 -0.08627374 -0.52238986]
 [ 0.50518185  0.16348607 -0.84738634]
 [-0.15851066  0.98276607  0.09510639]]
