# NumPy Arrays
*Numpy is a library of python that is used for Data analysis


In [1]:
import numpy as np

In [3]:
#creatng 1-D array from a list
list1= [1,2,3]
np.array(list1)

array([1, 2, 3])

In [4]:
#creating 2D array
matrice= [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#using pythons inbuilt fucntion to create an array

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#creating 1D array of zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
#creating 2 D array of zeroes
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#creating 1D array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
#creating 2D array of ones
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#creating an 5 x 5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
#generating a matrice of random numbers from uniform distribution
np.random.rand(5,5)

array([[0.48534375, 0.29835755, 0.23320153, 0.82677798, 0.84109328],
       [0.4876051 , 0.64372677, 0.50176558, 0.66518256, 0.84185341],
       [0.63459262, 0.29209732, 0.26302716, 0.48802105, 0.89333932],
       [0.85896112, 0.76911993, 0.34750337, 0.50581609, 0.115805  ],
       [0.66649554, 0.84351434, 0.71471067, 0.69140198, 0.6035287 ]])

In [22]:
#generating a matrice of random numbers from a normal distribution
np.random.randn(5,5)

array([[-0.25074861,  0.39223569,  2.63641456, -1.09367059,  0.41677086],
       [-0.26409096, -1.34195107,  0.5726705 , -2.08254939, -0.43696915],
       [-0.76362108, -0.893417  ,  0.05570286,  1.72224347,  0.9054012 ],
       [ 0.66675583,  1.61567127,  1.71356413, -1.72778472, -1.6717588 ],
       [ 0.44917955,  0.46343007, -2.32545863,  0.51334221, -1.80367867]])

In [25]:
#generating a matrice of random integers
np.random.randint(1,100,(5,5))

array([[32, 42, 72, 12, 19],
       [39, 14, 97, 43, 63],
       [37, 24, 35, 67, 30],
       [63, 94, 10, 92, 58],
       [44, 62, 11, 89, 35]])

In [29]:

array= np.random.randint(1,100,(25))
array

array([81, 94, 63, 33, 25, 73, 31, 74, 55, 94, 18, 35, 97, 25, 12, 35, 78,
       48, 79,  9,  5, 90, 33, 89, 36])

In [34]:
#reshaping an existing array into new dimension
array_reshape= array.reshape(5,5)
array_reshape

array([[81, 94, 63, 33, 25],
       [73, 31, 74, 55, 94],
       [18, 35, 97, 25, 12],
       [35, 78, 48, 79,  9],
       [ 5, 90, 33, 89, 36]])

In [35]:
#seeing the shape of an array
array_reshape.shape

(5, 5)