In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math

# Projections in R^2



In [23]:

# point b
b = np.array([4,1])

# line a
a = np.array([ 2, 5 ])

# beta
beta = (np.matrix.transpose(a)@b) / (np.matrix.transpose(a)@a)

c= b-(beta*a)
print("The line is:\n",a)
print("\n")
print("The point b is:\n",b)
print("\n")
print('The beta is:\n',beta)
print("The scaled version of line where it is orthogonal to point b is:\n",beta*a )
print("\n")
print("The line which is orthogonal to point b is\n",c)
print("\n")
#verifying if the lines are orthogonal with each other
print("The dot product between beta*a and c should be zero: \n",np.matrix.transpose(beta*a)@c)

The line is:
 [2 5]


The point b is:
 [4 1]


The beta is:
 0.4482758620689655
The scaled version of line where it is orthogonal to point b is:
 [0.89655172 2.24137931]


The line which is orthogonal to point b is
 [ 3.10344828 -1.24137931]


The dot product between beta*a and c should be zero: 
 8.881784197001252e-16


# Solving System of linear equations 


In [45]:
## Solving for x such that Ax is as close as it can be to b 

# sizes
m = 5
n = 3

# creating a vector b
b = np.random.randn(m,1)

# creating a matrix A
A = np.random.randn(m,n)

# solution using inverse
x = np.linalg.inv(np.matrix.transpose(A)@A) @ (np.matrix.transpose(A)@b)

print("The values of response variable is\n",b)
print("\n")
print("The slopes (or the values of x) of independent variables are:\n",x)
print("\n")
print("The predicted values are A@x:\n",A@x )
print("\n")
print("The residuals are:\n",b-(A@x1))


The values of response variable is
 [[0.44387863]
 [1.62662775]
 [1.2870895 ]
 [1.73499071]
 [0.96199694]]


The slopes (or the values of x) of independent variables are:
 [[ 0.0388251 ]
 [-0.49496042]
 [ 0.37044346]]


The predicted values are A@x:
 [[ 0.09313305]
 [ 0.23267913]
 [ 0.85446556]
 [-0.39406831]
 [ 0.82601419]]


The residuals are:
 [[0.40216727]
 [0.62960673]
 [0.17508009]
 [2.62869752]
 [0.83516834]]
